### ISSUE TITLE
adding some literature reference to the "analytic_data_model_an_introduction" notebook

### ISSUE THREAD

**Issue by mysl** [Kismuz/btgym#100]
hi @Kismuz ,  thanks a lot for sharing the educational notebook.  In order to get a deeper understanding of the methods in there,  it may be better to add some literature references in the notebook (including the notebooks upcoming) so that readers could potentially reach to the same page,  and engage in some meaningful discussions.  thanks!

**Comment by Kismuz** [comment]
yes, it is in progress

**Comment by Kismuz** [comment]
@mysl, done.

**Comment by mysl** [comment]
@Kismuz  thank you!
