### ISSUE TITLE
How is order_size calculated/used?

### ISSUE THREAD

**Issue by nisarahamedk** [Kismuz/btgym#102]
I am finding it difficult to understand how order_size param is used while placing orders. I am training the agent as in the UNREAL STACKED LSTM notebook on cryptocurrency BTC data.  I use below configuration for the strategy

![image](https://user-images.githubusercontent.com/34828828/53302366-75d0cc00-3883-11e9-973a-ab07242f548a.png)

However, when I analyze the episode chart in tensorboard, it doesn't look like it is buying or selling 1 BTC. Just to check, I changed the **order_size=10** and trained which should have failed as I don't have starting balance to trade that many BTC but it worked.

Am I missing something here? How is the order_size param actually used?.

I tried to find out as much info from Github issues, but no luck :(. Sorry if this has been already asked. Please direct me to the right issue if yes.

**Comment by nisarahamedk** [comment]
Embarrassingly enough, i just realized it's the **leverage** that is causing this behaviour.  I'll close this thread.

@Kismuz Have you ever thought about starting a **slack** or **discord** channel for easy collaboration so that people like me won't clutter the GitHub issues section. Just a suggestion.

Incredible work by the way 💯

**Comment by Kismuz** [comment]
> @Kismuz Have you ever thought about starting a **slack** or **discord** channel for easy collaboration so that people like me won't clutter the GitHub issues section. Just a suggestion.

[Done.](https://github.com/Kismuz/btgym#documentation-and-community)
