### ISSUE TITLE
example notebook for the pairs spread strategy

### ISSUE THREAD

**Issue by mysl** [Kismuz/btgym#106]
Hi @Kismuz ,  I noted there are some strategies e.g PairSpreadStrategy_1, SSAStrategy_0 etc added.  I am wondering if you could you add some example notebook about the state of the art result?  Or at least maybe you can add some tensorboard train/test stats/plots so that we can have a sense of what level of performance it can achieve currently?  Thanks a lot!

**Comment by Kismuz** [comment]
@mysl, those notebooks do exist but not brushed for publishing. [Un]luckily I'm currently involved in full-time project and just can't have time to properly describe and upload it. I'll try to make in nearest possible future.

**Comment by mysl** [comment]
@Kismuz  thanks!  looking forward to that. And congrats to your new adventure in your full time project
