### ISSUE TITLE
Global Server Time Shifted +1h

### ISSUE THREAD

**Issue by mobias17** [Kismuz/btgym#107]
When reading from timestamp and onverting to time format a shift of one hour occurs 

##### Files or part of package has been run:
--> btgym.dataserver.BTgymDataFeedServer

##### Expected behaviour:

The global time should be in line with the pandas df indexes

##### Actual behaviour:
reading from timestep is shifting time by one hour. e.g. when reading the example dataset (2016) the global clock is set to  2016-01-03 18:01:00 instead of 2016-01-03 17:01:00. 

##### Steps to reproduce:

1) Take a standard example workbook e.g. setting_uo_environment_full.ipnb
2) set verbose = 2
3) check NOTICE output "Initial global_time set to:"
4) Check the dataset that have been read in and compare the timestamps

##### Note:

A global UTC shift might actually be nice feature, after the global clock is sync.

Great Env so far. Still dicovering.

**Comment by Kismuz** [comment]
Closed due to long inactivity period.
