### ISSUE TITLE
Can i apply other RL framework to the gym and how to add indicators to the state space?

### ISSUE THREAD

**Issue by Ray-0403** [Kismuz/btgym#108]
hey, i am thinking about using stable-baselines to create the agent, how to do that? Also i want to use some my indicators as state space, how to add it?

**Comment by mobias17** [comment]
Hi,

let me give you my two cents worth thoughts, at least the sfor the second question. In general, the btgym is doing the general plumbing in the background for you and you can overwrite parts and replace them with yours. How to overwrite the statespace and e.g. add your own indicators is illustrated in the Examply "setting_up_environment_full.ipynb". You can also perform similar action in the research package I guess.

As for the stable-baseline I'd pass on hte answer as I am not familiar with that. Still, I assume that it should be possible. Read the documentation and spot the areas you need to overwrite.

**Comment by Ray-0403** [comment]
Thank you, i will look that file again

**Comment by developeralgo8888** [comment]
Hey Andrew, Stable-baselines is the same as Baselines except it usually has updated and current state of the art RL Algorithms compared to baselines. its a complete Fork of baselines

**Comment by Ray-0403** [comment]
Should i install both backtrader and btgym? since i saw that it import backtrader as bt, but after i install them all and run the code to test env, it shows no backtrader.indicators module, but there's indicators file in the backtrader file, i don't know how to fix it, can anyone help me? :)

**Comment by Kismuz** [comment]
@Ray-0403,
 > using stable-baselines to create the agent, how to do that? 

1. you can use btgym as standalone environment with gym-like API and plug it into existing rl framework i.e. using this part of the package: https://kismuz.github.io/btgym/intro.html#environment-engine-description

2. use async. training framework for btgym and adapt and plug-in any existing algorythm implementation that supports asynchronous updates: https://kismuz.github.io/btgym/intro.html#a3c-framework-description

> Also i want to use some my indicators as state space

this is the same as include your indicator to underlying backtrader strategy, see #31

> Should i install both backtrader and btgym

btgym depends on backtrader and installs it as one of  requirements

**Comment by Ray-0403** [comment]
Thank you very much:)

**Comment by Ray-0403** [comment]
There's something i don't understand in post #31. Is it means we should modify the code from backtrader to add the set_datalines() function ? and if it is, which exact file should we modify? 
Just getting confused about where to put that set_datalines() function.

**Comment by Ray-0403** [comment]
@Kismuz , i see the #31 and it just says how to modify Dev_Strat_4_11 to add other indicators/features. But if i don't use the agent btgym provided such as other RL framework, or use other agent btgym provided, how to add indicator? Is there a easy way that we can only modify a exact file from env to add indicators whatever the RL agent we use?
