### ISSUE TITLE
Custom datafeeed with custom BT strategy?

### ISSUE THREAD

**Issue by ogenev** [Kismuz/btgym#109]
Hello, what is the simplest way to add custom datafeed (bid/ask prices, bid/ask spread) instead of the standard OHLC bars and then use custom Backtrader strategy based on that?

**Comment by ogenev** [comment]
Should I just need to do:

1. edit BTGymBaseData parsing_params
2. edit BTgymRandomDataDomain parsing_params
3. override set_datalines and define strategy in BTgymBaseStrategy

**Comment by Kismuz** [comment]
@ogenev , yes exactly except that 1-2 are actually the same since you only need to change RandomDataDomain (or any other user-level domain class) parsing parameters; those changes will be propagated to base class.
See also: #45,  #8, #13

**Comment by ogenev** [comment]
Thank you! I'm a it confused how to use set_datalines method, can you please give an example with custom datalines, instead of olhc bars?

**Comment by Kismuz** [comment]
Closed due to long inactivity period.
