### ISSUE TITLE
Modify action space to support stoploss and takeprofit

### ISSUE THREAD

**Issue by Ray-0403** [Kismuz/btgym#111]
Since my Mac can't downgrade matploitlib to 2.0.2 , i need to move the btgym file to site-packages by myself and i need the  __init__.py file, thank you

**Comment by Kismuz** [comment]
@Ray-0403 , do you mean this one https://github.com/Kismuz/btgym/blob/master/btgym/__init__.py ?

**Comment by Ray-0403** [comment]
@Kismuz thx, and i have another question. When it comes to forex trading, setting stoploss and takeprofit points is important i think. How to modify the action space to support this? For each buy/sell order, i want the agent to choose a stoploss point from (30,40,50,60) and takeprofit point from(40,50,60,70,80,90,100, none). Can u give me a example about how to modify the code?

**Comment by Kismuz** [comment]
@Ray-0403,
> For each buy/sell order, i want the agent to choose a stoploss point from (30,40,50,60) and takeprofit point from(40,50,60,70,80,90,100, none)

I haven't implemented neither market orders nor stop/take points as action variants, so you have to develop it for yourself; one possible option is to utilize  discrete action space in a manner described in this paper: https://arxiv.org/pdf/1812.10252.pdf , see p.7 D. "Action space"

 >  only hold one position or no position for each time(for example, if the agent open a position after the first bar, it won't open a new position after the second bar...) and be able to choose the position size from a range 

this can also can be incorporated in a same way by multiplying action space dimensionality, but from my experience it is harder to learn than when agent emits consecutive orders of fixed size.

See also: #37

**Comment by Ray-0403** [comment]
@Kismuz , To implement stop/take points, what part of code should i modify? class BTgymEnv? Can u write a sample example of setting stop/take points?

**Comment by Kismuz** [comment]
Closed due to long inactivity period.
