### ISSUE TITLE
matplotlib upgrade?

### ISSUE THREAD

**Issue by Colin123** [Kismuz/btgym#118]
Use this template when reporting bugs, errors or unexpected behaviour. 
Override for general questions, feature requests, proposals etc.
----------------------------------------------------------------------

##### Running environment:
MacOs Mojave 10.14.6 (18G95)
Are there any plans to upgrade from matplotlib 2.0.2 to a newer version?
The standard headers are not found any more, related to these threads.
I'm trying to make some workarounds but if you are planning to upgrade matplotlib then I won't have to do that.

Thanks

https://docs.brew.sh/C++-Standard-Libraries
https://forums.developer.apple.com/thread/106114
Xcode 10 beta 4 - stdlibc++ headers not found;

**Comment by Kismuz** [comment]
@Colin123 , no I do not plan to make this upgrade due to: 
https://github.com/Kismuz/btgym/issues/19#issuecomment-347000601

if mem. leakage confirmed to be removed in latest release it can be done though

**Comment by Colin123** [comment]
ok thanks. i've switched to using an ubuntu vm in the meantime.
great work
