### ISSUE TITLE
Paper Trading testing on IB using Backtrader 

### ISSUE THREAD

**Issue by developeralgo8888** [Kismuz/btgym#12]
Is it possible to do Testing on Interactive Brokers (IB)  as is ? Just to test with actual trading environment without using actual funds. Backtrader uses IB or OANDA for trading and testing

**Comment by Kismuz** [comment]
This feature is not implemented yet. Though it is pretty straightforward [using backtrader functionality], it is quite useless until you figure out how to properly train agents using simulated environments; so it is not my priority at the moment.
