### ISSUE TITLE
PR Request for Docker addition

### ISSUE THREAD

**Issue by signalprime** [Kismuz/btgym#128]
I'm interested in contributing the first of 2 docker containers.  This is working for CPU based systems, and the next will be for GPU.
![image](https://user-images.githubusercontent.com/15487280/71738917-11c54f80-2e26-11ea-92f6-8b4b7d1bf251.png)

**Comment by Kismuz** [comment]
@signalprime , that's great! 
Would you prepare a pull request?

**Comment by signalprime** [comment]
Thanks!  Absolutely, just made the request.
