### ISSUE TITLE
Problem with dependencies in installation on window

### ISSUE THREAD

**Issue by tessanix** [Kismuz/btgym#137]
Hello! Firstly congratulation for this module project it seem very useful!

Unfortunately I have a problem in the installation. I use Anaconda as IDE and when I launch a pip instal btgym on my anaconda powershell prompt I have this error :
`(tensorflow_env) PS C:\Users\Tesso> pip install C:\Users\Tesso\OneDrive\Bureau\btgym-master
Processing c:\users\tesso\onedrive\bureau\btgym-master
Requirement already satisfied: tensorflow>=1.5 in d:\anaconda3\envs\tensorflow_env\lib\site-packages (from btgym==0.0.8) (2.1.0)
Collecting opencv-python
  Using cached opencv_python-4.2.0.34-cp37-cp37m-win_amd64.whl (33.0 MB)
Requirement already satisfied: gym[atari] in d:\anaconda3\envs\tensorflow_env\lib\site-packages (from btgym==0.0.8) (0.17.1)
  WARNING: gym 0.17.1 does not provide the extra 'atari'
Collecting backtrader
  Using cached backtrader-1.9.74.123-py2.py3-none-any.whl (411 kB)
Requirement already satisfied: pyzmq in d:\anaconda3\envs\tensorflow_env\lib\site-packages (from btgym==0.0.8) (18.1.1)
Collecting matplotlib<=2.0.2
  Using cached matplotlib-2.0.2.tar.gz (53.9 MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda3\envs\tensorflow_env\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Tesso\\AppData\\Local\\Temp\\pip-install-j_ae94ia\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\Tesso\\AppData\\Local\\Temp\\pip-install-j_ae94ia\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Tesso\AppData\Local\Temp\pip-install-j_ae94ia\matplotlib\pip-egg-info'
         cwd: C:\Users\Tesso\AppData\Local\Temp\pip-install-j_ae94ia\matplotlib\
    Complete output (63 lines):
    ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [2.0.2]
                    python: yes [3.7.7 (default, Apr 15 2020, 05:09:04) [MSC
                            v.1916 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.18.1]
                       six: yes [using six version 1.14.0]
                  dateutil: yes [using dateutil version 2.8.1]
               functools32: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [using pytz version 2019.3]
                    cycler: yes [using cycler version 0.10.0]
                   tornado: yes [using tornado version 6.0.4]
                 pyparsing: yes [using pyparsing version 2.4.6]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: yes [installing, Qt: 5.9.6, PyQt: 5.9.6]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I think I just have to include freetype.h and png.h files in some folder but I don't know which one. 
Can you help me please?

**Comment by Kismuz** [comment]
@tessanix ,s mentioned in readme,  bygym does not seem to work correctly under windows, sorry for that.
https://github.com/Kismuz/btgym#issues
your particular error is about failed attempt to build earlier-version matplotlib
see also: #17
