### ISSUE TITLE
Tiny typo

### ISSUE THREAD

**Issue by MauricioFilgueiras** [Kismuz/btgym#14]
https://github.com/Kismuz/btgym/blob/d5c3236a3283d24291f25fb5c571e0315eb59dc1/btgym/envs/backtrader.py#L662

dormat(mode) > format(mode)

` raise ValueError('Unexpected render mode {}'.format(mode))`

**Comment by Kismuz** [comment]
@MauricioFilgueiras,  thanks! Fixed.
