### ISSUE TITLE
Problem when run tensorboard_monitor.ipynb

### ISSUE THREAD

**Issue by peterballdd** [Kismuz/btgym#16]
I run tensorborad_monitor.ipynb and found this problem below: Please help

UnsupportedMode                           Traceback (most recent call last)
<ipython-input-4-85159ed01baa> in <module>()
     79             images_monitor.write(
     80                 feed_dict={'human': env.render('human')[None,:],
---> 81                            'agent': env.render('agent')[None,:],
     82                           },
     83                 global_step=global_step + last_i['step'],

~/.local/lib/python3.5/site-packages/gym/core.py in render(self, mode, close)
    147                 raise error.UnsupportedMode('{} does not support rendering (requested mode: {})'.format(self, mode))
    148             elif mode not in modes:
--> 149                 raise error.UnsupportedMode('Unsupported rendering mode: {}. (Supported modes for {}: {})'.format(mode, self, modes))
    150         return self._render(mode=mode, close=close)
    151 

UnsupportedMode: Unsupported rendering mode: agent. (Supported modes for <BTgymEnv instance>: ['human', 'episode'])

**Comment by Kismuz** [comment]
@peterballdd,
It seems I just forgot to update example code to be consistent with new version of package. Sorry for that. Code is now up-to-date, git-pull and update BTgym to run it.

**Comment by peterballdd** [comment]
Thank you very much
