### ISSUE TITLE
Question Performance

### ISSUE THREAD

**Issue by joaosalvado10** [Kismuz/btgym#18]
Hello first of all thank you for your contribution.
I would like to know what is your opinion concerning using A3C to predict stock market and also for a certain equity what kind of features should be taken into account? High , low, open close ?

Thank you 
João Salvado

**Comment by Kismuz** [comment]
@joaosalvado10 ,
First,  I'll be a bit bore but it would be correct to state that Reinforcement Learning setting is about learning to act consistently to achieve certain end-goal,  not about  'predicting'.
Second, to my current understanding [Open, High, Low] is sufficient as raw observation  to estimate market 'signal features', which one can think of as  'external market state'. Also, from my experience, it's crucial to augment environment observation state with portfolio/account performance statistics: current value, unrealised profit/loss, position exposure etc. which can be referred as 'internal broker state'.
I currently working on some examples of such strategies and plan to publish results an about week or so.

**Comment by joaosalvado10** [comment]
Thank you for your answer!
Joao Salvado

**Comment by Kismuz** [comment]
@joaosalvado10 
You can check ideas mentioned above in:
https://github.com/Kismuz/btgym/blob/master/btgym/research/strategy_4.py
and in working example: 
https://github.com/Kismuz/btgym/blob/master/examples/a3c_random_on_synth_or_real_data_4_6.ipynb
