### ISSUE TITLE
Is there a roadmap for using cryptocurrency trading data?

### ISSUE THREAD

**Issue by djoffrey** [Kismuz/btgym#25]

**Comment by Kismuz** [comment]
@djoffrey,  
Short: 
- not yet

Expanded:
- actually you can use any data, it is matter of setting up csv parser and tuning up observation calc. Here is discussions somewhat related to BTC and  parsing other timeframes: 
https://github.com/Kismuz/btgym/issues/8
https://github.com/Kismuz/btgym/issues/13

**Comment by joaosalvado10** [comment]
Hello,  @Kismuz I changed the code in order to be able to use daily data frames instead of intradaily data frames. I can see that the episode.data contains a correct sample of my daily dataframe  and this one is accepted however it remains in global step 0 and always geting new random samples.
So the train never starts. Any idea how can I solve this? 

Here is my csv file:

https://wetransfer.com/downloads/06fe5cebd50f7c1fe0c7da1084a0900d20171220124556/04abcae779bab94c6d295838057d90ac20171220124556/0315b8

**Comment by Kismuz** [comment]
@joaosalvado10  - any details? what script you are running? shots of terminal  and tensor_board output?

**Comment by joaosalvado10** [comment]
@Kismuz problem solved ;)
Now I am trying to add other features already in csv file as other issues that you already refer to.

**Comment by joaosalvado10** [comment]
I am runing the unreal script.
Here is the file that I am using at the moment and the error that i am getting.
I can clearly see that it generates correctly the dataframe however i am unable to proceed to training.

https://we.tl/ynnjaUL9Cx

**Comment by kazi308** [comment]
Hi Kismuz,

I have found https://github.com/bartosh/backtrader/tree/ccxt which has support for a wide range of crypto exchanges. I would be interested to know if btgym supports the same exchanges as backtrader. Thank you for your work!

**Comment by Kismuz** [comment]
@kazi308,
basically BTGym is RL wrapper around backtrader and has been designed to inherit  support for cc, live trading etc. by default , though I'm still busy developing RL framework itself and have not reached this field so far.
Another promising direction is utilising exisiting domain knowledge in form of already developed traditional trading strategies and built-in backtrader indicators  as additional or primary state inputs to RL agent.

**Comment by djoffrey** [comment]
@Kismuz 
I did a little dirty hack to datafeed to make cryptocurrency data work, and I think we need a little abstraction of data input mechanism, such as

function read_csv => function load_data would be nicer, I think.

**Comment by Kismuz** [comment]
@djoffrey ,
> I did a little dirty hack to datafeed to make cryptocurrency data work
Can you share details of what data you use and mods have been done?

> we need a little abstraction of data input mechanism
You mean adding other than csv source of input or more changing parsing approach to existing data source?
General data pipe rework is my priority at the moment, though I'm focused on enabling data hierarchy from the meta-learning point of view. [General changes has been pushed](https://github.com/Kismuz/btgym#news) and some refining is in progress,  any suggestions and contributions are welcome.

**Comment by djoffrey** [comment]
@Kismuz 

> Can you share details of what data you use and mods have been done?

My dataset is a pandas.DataFrame object with datetime index, and OHLCV columns, I manually replace "data" of BTGymDataSet and related member vars etc.

> You mean adding other than csv source of input or more changing parsing approach to existing data source?

Yes, I think a general data pipeline is quite important.

**Comment by aaron8tang** [comment]
Hi , @joaosalvado10 ,could you please give a simple example to show how to use daily data with btgym? I cannot figure it out yet. Thanks!
