### ISSUE TITLE
RL example strategy

### ISSUE THREAD

**Issue by Amarchuk** [Kismuz/btgym#3]
Hi, thanks for another new great gym environment!

Its not actual issue, more like question:
I am curious about actual RL trained strategies examples (not necessary profitable), because I didn't find any and OpenAI didn't pay much attention to financial gyms. It will be much easier to learn on existed examples how tune architecture or parameters. I would be very grateful if you point me out useful links if you know some. Thanks

**Comment by Kismuz** [comment]
Neither me. That's why I wrote this environment.
There is an evident shortage of valuable information on this topic. 
Look at
https://github.com/hackthemarket/gym-trading
for some working examples.

**Comment by Amarchuk** [comment]
Thanks a lot @Kismuz!

You maybe also interested in https://github.com/Henry-bee/gym_trading, which is a modification of project you mention.
