### ISSUE TITLE
inherit BTgymDataset to use binary feed

### ISSUE THREAD

**Issue by GaelReinaudi** [Kismuz/btgym#41]
Hi,
when I try to derivate BTgymDataset in order to use my own datasource in this way: https://www.backtrader.com/blog/posts/2015-08-11-datafeed-development/datafeed-development.html

I get btgym complaining about the NoneType being not iterable. It is trying to read a csv file even though I did override the necessary methods such as load.

Is there a use case I am missing so that I can use a non csv source of data in the same way backtrader does in the example linked above?
Thx.

**Comment by Kismuz** [comment]
@GaelReinaudi,
would you please specify which methods of base class has been overridden and how?

what behaviour you expected?

what exact error log you get?

Related: #32, #25, #13, #12
