### ISSUE TITLE
Installing with `python3 setup.py develop --user` breaks pip

### ISSUE THREAD

**Issue by cuihantao** [Kismuz/btgym#42]
Use this template when reporting bugs, errors or unexpected behaviour. 
Override for general questions, feature requests, proposals etc.
----------------------------------------------------------------------

##### Running environment:
Ubuntu 16.10 LTS
Python 3.5/3.6

##### Files or part of package has been run:
setup.py

##### Expected behaviour:
Everything is expected to work as normal.

##### Actual behaviour:
After running `python3 setup.py develop --user`, pip3 breaks with import errors. 

Seems to be related to this one https://github.com/pypa/setuptools/issues/885
##### Steps to reproduce:

**Comment by Kismuz** [comment]
@cuihantao, 
seems to be related to `sutuptools` itself, not btgym package, isn't it?

Recommended workaround from https://github.com/conda/conda/issues/6879 :
```
conda update setuptools
easy_install pip
```

BTW, does executing:
```
cd btgym

pip install -e .
```
throws same error?

**Comment by cuihantao** [comment]
By using 
```
cd btgym

pip install -e .
```
everything works fine.

Seems to be a bug related to `setuptools`. I'm gonna close this ticket. Probably you may mention not to run `python setup.py` in the README.
