### ISSUE TITLE
Can I use the trained agent to generate Actions

### ISSUE THREAD

**Issue by sharpwood** [Kismuz/btgym#49]
I have trained the model. Can I use the trained agent to generate Actions in the Running agent section of setting_up_environment_basic?

**Comment by huminpurin** [comment]
you may want to check this thread: https://github.com/Kismuz/btgym/issues/23

**Comment by sharpwood** [comment]
@huminpurin  thanks mate. Can I add you qq or e-mail to ask about it?

**Comment by Kismuz** [comment]
See also #46, #40
