### ISSUE TITLE
BTgymStrategy not defined in Quickstart-Maximum environment flexibility

### ISSUE THREAD

**Issue by arisliang** [Kismuz/btgym#52]
In the documentation (https://kismuz.github.io/btgym/intro.html#quickstart), Maximum environment flexibility section, `MyCerebro.addstrategy(BTgymStrategy,...`.

However, BTgymStrategy is not defined here. Do we need to define it first?

**Comment by Kismuz** [comment]
@arisliang, it is typo, should actually read `MyCerebro.addstrategy(BTgymBaseStrategy` which has been imported, thanks for mentioning;

**Comment by arisliang** [comment]
Excellent, thanks for clarifying.
