### ISSUE TITLE
Ingesting real-time streaming data feed (Live) from Interactive Broker  instead of .CSV 

### ISSUE THREAD

**Issue by developeralgo8888** [Kismuz/btgym#55]
@Kismuz ,

Can you give some insights on how best to ingest realtime streaming FOREX data feed from Interactive Broker into btgym instead of .CSV  for continuous online training , testing and trading 

- Currently i believe we have .CSV Data ==> Btgym (offline training & validation )==> signals/Action ( Buy /Sell/Hold)

what i am trying working on . 

With BT , it already has infrastructure in place to get realtime streaming datafeed from IB, so that's not an issue. my issue is how to integrate it with BTGYM infrastructure with minimal changes to Btgym core structure . ( Less work/maintenance  means more time to work on improving and testing Algorithms offline ) 

Interactive Brokers Realtime Data feed =>  DB for persistence ( Influx/Postgresql/Mongo) ==> Btgym  (online training & validation ) ==> signals/Action ( Buy /Sell/Hold) ==> Trade sent to interactive Brokers

**Comment by developeralgo8888** [comment]
@Kismuz , Thanks for that great explanation . I was thinking on having a trained model and just to validate/test  it with real-time streaming data to trade.  I do understand live online training of streaming data is really massively expensive  .

initial thought of a continuous loop:

IB Realtime Streaming data ==> btgym ==> continuously update and validate/test offline Trained model ==> get buy/sell signals ==> send live trade  ==> IB 

Continuous updating and validating/test offline model will require some rolling window model . Do we do a continuous offline training of model and update or append or  rewrite the live trading model every 15 mins, 30 mins or 1 hour depending on our trading timeframe  ?

**Comment by Kismuz** [comment]
@developeralgo8888 ,
>  Do we do a continuous offline training of model and update or append or rewrite the live trading model every 15 mins, 30 mins or 1 hour depending on our trading timeframe ?

- basically, yes. But with multi-worker algorithms like A3C or A2C it is possible to do better and implement continuous updating of a model via separation worker's tasks: say, one worker is real-time validator while others are running training loop on data available up to present point. Following A3C base update routine, validator can update learned behaviour policy after every rollout or even after single step (and we still got, say,  15 min to retrain model given new data). Similar approach (for off-policy training via exp.replay) is already implemented in recent DeepMind REACTOR algorithm, see paragraph 3.4 of the paper:
https://arxiv.org/abs/1704.04651

**Comment by developeralgo8888** [comment]
@Kismuz , thanks for the great clarification . well appreciated
