### ISSUE TITLE
Unable to install BTGym

### ISSUE THREAD

**Issue by pralakk16** [Kismuz/btgym#59]
Use this template when reporting bugs, errors or unexpected behaviour. 
Override for general questions, feature requests, proposals etc.
----------------------------------------------------------------------

##### Steps to reproduce:

**Comment by pralakk16** [comment]
I am unable to install BTGym on both Ubuntu and Windows. Can you please help

**Comment by Kismuz** [comment]
@pralakk16, you actually suppoded to fill form above with appropriate details; I'm unable to help  without any details. :) put any error logs under `Actual behaviour:` section.

**Comment by pralakk16** [comment]
Ok Thank you, I actually got it working

**Comment by pralakk16** [comment]
It looks like the gym[atari] file was not building because cmake was not installed
