### ISSUE TITLE
Please Implement the live trading part as you continue to do research 

### ISSUE THREAD

**Issue by developeralgo8888** [Kismuz/btgym#61]
I am starting to get more into your research since i have the same mindset in terms of your RL research and its application to real trading world. I appreciate the great work you have done. 

More traders , researchers and hobbists are going to get more interested if you can have the live trading module and realtime data through Interactive brokers working first as you continue with implementing other pieces in the package . Let them play around with it and we continue to research and expand the BTGYM package , they will share their experiences on what works and what does not. 

Without the Live trading and Realtime datafeed hook , then many will just look at it as another python package going nowhere. For us who are in AI field, your research and work in financial trading domain using RL is awesome and great. Thank you for that and continue your great work, we support you .

**Comment by Kismuz** [comment]
@developeralgo8888, do you have an experience working with interactive brokers API? I browsed through docs but didn't figured out  either it's possible to use API with demo account id.

**Comment by developeralgo8888** [comment]
Yes, it is possible . Just download the TWS client software  and just use default  username and password  which is edemo  /demouser. Note this is not live it simply replays the previous market. 

You need a paper trading account to do actual real-time testing which means you need an actual REAL account. REAL  IB account comes with an independent paper trading account for your testing . Let me know if you need one for testing i can configure my paper trading  account for a brief testing for you  ( 1 month ) . Email me privately and i will set it up and let you know the details

**Comment by developeralgo8888** [comment]
@Kismuz , Yes i have used backtrader ibstore interface class. So far no  issues . It handles data from IB very well and pretty fast .

**Comment by developeralgo8888** [comment]
When the implementation is ready let me know so that i can set up the testing paper trading account .

**Comment by mysl** [comment]
@Kismuz ,  I think backtrader also supports Oanda live trading,  and you can have paper trading account from Oanda for free

**Comment by snipe75** [comment]
Did you guys consider doing cryptocurrency trading ? Binance exchange for example allows data acquisition even without registration, and the APIs are quite simple and effective. I made a small notebook that saves .csvs. Perhaps sentiment analysis of twitter/reddit or order book monitoring would increase model effectiveness.
