### ISSUE TITLE
question about reuse_encoder_params

### ISSUE THREAD

**Issue by mysl** [Kismuz/btgym#63]
@Kismuz , hi, I have a question w.r.t reuse_encoder_params in stacked_lstm.py,  my understanding is that you want to control sharing the conv parameters across all external streams.  However, it looks like that different streams of external states use different names, thus they will be in different variable scopes right?  Will the reuse take effect or did I miss or misunderstand anything? thanks!

**Comment by Kismuz** [comment]
@mysl , good catch, thank you!
Corrected, update.

**Comment by mysl** [comment]
@Kismuz ,  thanks.
