### ISSUE TITLE
guided_a3c example no longer works after update

### ISSUE THREAD

**Issue by ALevitskyy** [Kismuz/btgym#64]
This is the problem:

btgym/research/verbose_env_runner.py", line 57, in VerboseEnvRunnerFn
    last_action = np.zeros(env.action_space.n)
AttributeError: 'ActionDictSpace' object has no attribute 'n'

**Comment by Kismuz** [comment]
@ALevitskyy , fixed; some rendering temporaly disabled though; sorry for late rep - been busy repairing my broken workstation.
