### ISSUE TITLE
tensorboard monitor not found

### ISSUE THREAD

**Issue by shisi-cc** [Kismuz/btgym#66]
Hi! I have seen tensorboard monitor introduction in btgym/example, but the hyperlink is invalid and I couldn't find any code or ipynb files. Is it deprecated or located somewhere else? Thank you

**Comment by Kismuz** [comment]
@shisi-cc, it's indeed deprecated; now it' far more convenient to use tb in a usual way; thank you for pointing link out.

**Comment by shisi-cc** [comment]
Ok. Thank you!
