### ISSUE TITLE
 if 'raw' in self.params['strategy']['state_shape'].keys(): AttributeError: 'tuple' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Kalelv45** [Kismuz/btgym#68]
Use this template when reporting bugs, errors or unexpected behaviour. 
Override for general questions, feature requests, proposals etc.
----------------------------------------------------------------------
Hi, having some problem while running env in GYM preferred way. Running the code as in documentation gets me this error: 
##### Running environment:
if 'raw' in self.params['strategy']['state_shape'].keys():
AttributeError: 'tuple' object has no attribute 'keys'

**Comment by Kalelv45** [comment]
Thanks to you! Tried to reach out and communicate with you, but don't know how. 
Thanks for you work!

**Comment by Kismuz** [comment]
@Kalelv45 -  updated personal profile with public email.
