### ISSUE TITLE
How to render when using Launcher

### ISSUE THREAD

**Issue by snipe75** [Kismuz/btgym#69]
Hello, I've been running the guided A3C notebook example and I'm wondering how to render the results ? engine.render() returns "AttributeError: 'Cerebro' object has no attribute '_exactbars'".
 How to plot in general when using Launcher ?

 Thanks and best regards

**Comment by Kismuz** [comment]
@snipe75,
when Launcher framework is used, all the renderings are collected via summaries mechanism of tensorflow, get stored in summaries directory and displayed by tensorboard monitor under 'images' tab. If you want so save some of it as image file, tensorboard pages provide direct links. Same is true for all other summaries. Refer to tensorflow/tensorboard manual if you need fruther details.

**Comment by snipe75** [comment]
Great, thanks for the quick response !
