### ISSUE TITLE
How to feed daily quote data to BTgym?

### ISSUE THREAD

**Issue by aaron8tang** [Kismuz/btgym#70]
I'm a newbie to BTgym, I just have EOD data and want to try BTgym. I'm not sure how to configure the parameters,such as start_weekdays,episode_duration,start_00 etc. . Could you please give a simple example to feed daily quote data to BTgym? Thanks in advance!

**Comment by snipe75** [comment]
As far as I know, you should save recent stock prices into a csv. Then you can
run the Guided A3C notebook and just replace the default dataset like so:

dataset = BTgymDataset(
    filename="YOUR FILE LOCATION\file.csv"
)
Then you can view agent action in tensorboard. As far as getting the result back into python so you can manipulate it further.. I'd like to know how to do that as well.

**Comment by aaron8tang** [comment]
Thanks, I've figured it out.
