### ISSUE TITLE
AttributError

### ISSUE THREAD

**Issue by macd2** [Kismuz/btgym#87]
Hey There im just pulled the latest version and getting:

`AttributeError: 'ActionDictSpace' object has no attribute 'n'`

##### Running environment:
i used the examples to initialize the env

##### Files or part of package has been run:
i fails here: 
`self.env.action_space.n`

in addition im getting this warning 'WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.'

which has to do with h5py but is surely not related to this issue.

Thanks for help

**Comment by Kismuz** [comment]
@macd2, which example exactly is throwing this?
