### ISSUE TITLE
Tensorboard Analysis Discussion

### ISSUE THREAD

**Issue by JacobHanouna** [Kismuz/btgym#90]
I'm currently training a basic model (~500k steps so far) just to get an intuition of the evaluation process.
there are 2 main tabs that hold most of the information, Scalars and Images.

In the scalar section, at first glance the metrics looks a bit chaotic (better after smoothing).
but I wonder what would be a good expected result for each metric (or at least what should the main ones look like)

In the image section we have the backtrader episode summary (which is super cool to see!!!)
and 3 more images (external, internal and human) but i'm not sure what to look for in them.

those are more general questions about the analysis process but I also notice a few things that might be more model specific.

the model have a SMA-1024 which is about a third of the length of the episode size i choose. the problem is that backtrader is waiting for the longest indicator period before making the first decision (part of backtrader design) so a third of the episode is wasted. don't know if there is anything that can be done?

another thing i notice is that roughly 20% of the times not a single action is being made in the episode. is this normal behavior?

**Comment by Kismuz** [comment]
@JacobHanouna,
> 3 more images (external, internal and human) 

those shows single last env. observation of the episode as seen by:
 - human: external part (price data) in simple graphic form (is we would plot it);
- external: external (price) data seen by agent after preprocessing (input features);
- internal: internal part of environment observation (broker statistics) input to agent;

two later presented as map-image but could be rendered as plots as well by setting env setup kwarg: `render_state_as_image=False`

these can be inspected to exclude common errors: flat or inconsistent inputs, min/max values ranges (shown in titles)  etc.

> backtrader is waiting for the longest indicator period before making the first decision ... if there is anything that can be done?

- yes, to compose first observation to be precise;
- no, except to enlarge episode duration or to introduce another signal decomposition scheme. Btw I collaborate with guys who runs traditional stat. arb strategies with real allocation and they use initial periods up to 7000 - 10000 to stabilise signals estimations :)
